apiVersion: v1
kind: Service
metadata:
  name: test-website-service
  namespace: test-website
spec:
  type: NodePort
  selector:
    app: test-website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
